"""Assemble a PipelineSpec into a full, valid azure-pipelines.yml document."""

from __future__ import annotations

import yaml

from azpipegen.spec import PipelineSpec
from azpipegen.templates import build_steps, deploy_stage, lint_steps, test_steps


class RenderError(Exception):
    pass


class _PipelineDumper(yaml.SafeDumper):
    """A SafeDumper that renders multi-line strings (our `script:` blocks) as
    literal block scalars ('script: |') instead of folded/quoted one-liners,
    so the generated YAML reads the way a human would write it by hand.
    """


def _str_presenter(dumper: yaml.Dumper, data: str):
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


_PipelineDumper.add_representer(str, _str_presenter)


def render(spec: PipelineSpec) -> str:
    """Render a PipelineSpec to a YAML string. Raises RenderError on an invalid spec."""
    errors = spec.validate()
    if errors:
        raise RenderError("; ".join(errors))

    build_job_steps = build_steps(spec) + lint_steps(spec) + test_steps(spec)

    pipeline: dict = {
        "trigger": {"branches": {"include": list(spec.trigger_branches)}},
        "pool": {"vmImage": spec.pool_vm_image},
        "stages": [
            {
                "stage": "Build",
                "displayName": "Build and test",
                "jobs": [
                    {
                        "job": "BuildJob",
                        "displayName": "Build",
                        "pool": {"vmImage": spec.pool_vm_image},
                        "steps": build_job_steps,
                    }
                ],
            }
        ],
    }
    # Once we introduce a second stage, "pool" moves from top-level onto each
    # stage/job (Azure Pipelines allows both, but per-job is unambiguous once
    # there's more than one stage) — drop the now-redundant top-level pool.
    stage2 = deploy_stage(spec)
    if stage2:
        pipeline["stages"].append(stage2)
        del pipeline["pool"]

    yaml_text = yaml.dump(
        pipeline, Dumper=_PipelineDumper, sort_keys=False, default_flow_style=False, width=100
    )

    # Fail loudly rather than hand back something that merely "renders" but
    # isn't valid YAML -- round-trip it before returning.
    try:
        yaml.safe_load(yaml_text)
    except yaml.YAMLError as exc:  # pragma: no cover - defensive, templates are hand-verified
        raise RenderError(f"Generated YAML failed to parse: {exc}") from exc

    header_lines = ["# Generated by azpipegen — https://github.com/i-ankitkumar/azure-pipeline-generator"]
    if spec.uncertainties:
        header_lines.append("#")
        header_lines.append("# NOTE: a few things in the description weren't clear enough to act on:")
        for note in spec.uncertainties:
            header_lines.append(f"#   - {note}")
    header_lines.append("")

    return "\n".join(header_lines) + yaml_text
